name: 'GitHub Graph Data Collector'
description: 'Collects GitHub organization data and saves it to a CSV file'
author: 'Gabriel Ramirez'
branding:
  icon: 'git-branch'
  color: 'blue'

inputs:
  github_token:
    description: 'GitHub token with read access to orgs'
    required: true
  orgs_file:
    description: 'Path to the JSON file containing organization information'
    required: true
    default: 'orgs.json'
  since_iso:
    description: 'Start date in ISO format (YYYY-MM-DD or YYYY-MM-DDTHH:MM:SS)'
    required: false
  until_iso:
    description: 'End date in ISO format (YYYY-MM-DD or YYYY-MM-DDTHH:MM:SS)'
    required: false
  output_file:
    description: 'Output file path for CSV'
    required: false
    default: 'github_data.csv'
  commit_message:
    description: 'Commit message for the CSV file update'
    required: false
    default: 'Update GitHub organization data'

runs:
  using: 'composite'
  steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'

    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        # Install the published package (builds from action source when used locally)
        python -m pip install "${{ github.action_path }}"

    - name: Run collection script
      shell: bash
      run: |
        export GITHUB_TOKEN="${{ inputs.github_token }}"
        COMMAND="gh-graph-explorer collect --orgs ${{ inputs.orgs_file }} --output csv --output-file ${{ inputs.output_file }}"
        if [ -n "${{ inputs.since_iso }}" ]; then
          COMMAND="$COMMAND --since-iso ${{ inputs.since_iso }}"
        fi
        if [ -n "${{ inputs.until_iso }}" ]; then
          COMMAND="$COMMAND --until-iso ${{ inputs.until_iso }}"
        fi
        $COMMAND
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}

    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: ${{ inputs.commit_message }}
        file_pattern: ${{ inputs.output_file }}
