version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD:-password}
    volumes:
      - ./data:/app/data
    depends_on:
      - neo4j
    command: --repos /app/data/repos.json --output neo4j --neo4j-uri bolt://neo4j:7687

  neo4j:
    image: neo4j:5.18.0
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    environment:
      - NEO4J_AUTH=neo4j/${NEO4J_PASSWORD:-password}
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import
      - neo4j_plugins:/plugins

volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_import:
  neo4j_plugins: