version: '3'

services:
  mcp_server:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD:-password}
      - MCP_TRANSPORT=sse

    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    depends_on:
      - neo4j
    command: python mcp_server.py
  
  neo4j:
    image: neo4j:latest
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    environment:
      - NEO4J_AUTH=neo4j/${NEO4J_PASSWORD:-password}
      - NEO4J_PLUGINS=["graph-data-science"]
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import
      - neo4j_plugins:/plugins


volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_import:
  neo4j_plugins: